### PR TITLE
Fixed 3 Skins to work with TBC AddOns

### PR DESCRIPTION
**Pull request by fuba82**
Fixed 3 Skins to work with TBC AddOns:

- AdvancedTradeSkillWindow v0.6.9
- BugSack v2.3.0.70977
- FishingBuddy v0.9.4m

### CODE REVIEW

**Comment by fuba82** [comment]
also fixed some other addon skins

**Comment by Crumdidlyumshis** [comment]
Looks nice! Could you please convert the spaces in all the updates to tabs to keep the workflow moving? Otherwise, great job!

**Comment by fuba82** [comment]
hopefully updated all the speces with tabs

**Comment by Crumdidlyumshis** [comment]
Thank you!

**Comment by fuba82** [comment]
> Thank you!

i have to thank **YOU** for the great work ^^

**Pull request merged**
